# Application name
spring.application.name=online-voting-system

# Server port
server.port=8080

# MongoDB connection settings
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=voting_db
